import type { Metadata } from "next";
import { Inter, Tektur } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { UserContextProvider } from "./Context/user";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const tektur = Tektur({
  subsets: ["latin"],
  weight: "700",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={tektur.className}>
        <UserContextProvider>
          <main>{children}</main>
          <Toaster />
        </UserContextProvider>
      </body>
    </html>
  );
}
