import type { Metadata } from "next";
import { Inter, Russo_One, Tektur } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const russoOne = Russo_One({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const tektur = Tektur({
  subsets: ["latin"],
  // weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={tektur.className}>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
